### PR TITLE
Refactor to use ngrx facade pattern

### PR DESCRIPTION
**Pull request by ThomasBurleson**
Use facade API to hide all usages of ngrx store & effects from view layers

*  update README.md to include firebase setup grfxs/instructions
*  use barrels to simplify access of post/user functionality
*  use `utils/rxjs.operators.ts` for centralized imports
*  move effects functionality into `post.facade.ts` and `user.facade.ts` classes
*  use `init$` effects to auto-login and auto-load posts
*  create `AppStateModule` and register facades as providers and effects
*  simplify App view to use facades only

### CODE REVIEW

**Comment by sstorie** [comment]
This is really interesting to see after having not looked too much at ngrx for a while. I'm a bit puzzled though about how to handle the list observables provided by AngularFire2 with the ngrx pattern. This all makes sense with simple "get an object once" type activity, but the real-time nature of firebase is throwing me off.

For example, I have a list of friend statuses in my app. Once the user authenticates I wire up an observable to the firebase path for the statuses, and as the data in that path changes my views respond to the new list of statuses. How would that scenario work with ngrx?

One thought I had was to just have another service that waits for the authenticated user, and then emits "success" actions when the data changes, or "fail" actions if something goes wrong. That's basically what I do now, but I'd be adding the store in the middle, so at least my view layer wouldn't take a direct dependency on the service listening to firebase. With that though I'm not clear on how effects come into play, if they do at all.

**Edit**
Here's something I found that might help my thinking - https://stackoverflow.com/a/43035904/571237 

Here's the gist of the answer:
```
@Effect()
refreshItems$ = this.af.auth
  .switchMap((authState) => authState ?
    this.af.database
      .list('/items')
      .map(items => ({ type: 'REFRESH_ITEMS', payload: items })) :
    Observable.of({ type: 'REFRESH_ITEMS', payload: [] })
  );
```
So there you don't worry about an action triggering the refresh of the items, but instead leverage the power of AngularFire to create the effect. Does that sound reasonable based on your experience?

**Comment by codediodeio** [comment]
@ThomasBurleson Thanks for the awesome improvements! I only made one change to the user $init effect to use GET_USER, instead of GOOGLE_LOGIN. The app should check for an existing auth session and let the user trigger the login process manually.

**Comment by ThomasBurleson** [comment]
@codediodeio - COOL!

**Comment by codediodeio** [comment]
@sstorie You could create an action and effect called GET_USER_STATUSES with the current uid as the payload, assuming you have the user's friends nested under the current uid. In the effect, you could then query firebase and have a realtime connection to the data. I plan on adding more features to this repo in the future with the goal of showcasing a large variety of examples, including user-data relationships.

**Comment by sstorie** [comment]
@codediodeio Thanks for the suggestion. I plan to keep working on this in my app to see what feels right. Hopefully I can contribute back like @ThomasBurleson as you move along in your own efforts.

**Comment by codediodeio** [comment]
@sstorie That would be great!

**Pull request merged**
